apiVersion: v1
kind: Pod
metadata:
  name: flask-pod-with-secret
  labels:
    app: flask-with-secret
spec:
  containers:
    - name: flask-with-secret
      image: quay.io/iamgini/my-flask-app:1.0
      env:
        - name: PASSWORD_ENV_VAR # name of env variable
          valueFrom:
            secretKeyRef:
              name: my-first-secret # name of secret object
              key: db_password # name of key in secret object 